services:
  # --- PostgreSQL Database ---
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: teamdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Backend/DeLaSursa/docker/initdb:/docker-entrypoint-initdb.d

  # --- Spring Boot Backend ---
  backend:
    build:a
      context: ./Backend/DeLaSursa
    container_name: spring-app
    depends_on:
      - postgres
    env_file: .env  
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/teamdb
      DB_USER: postgres
      DB_PASS: yourpassword
      JWT_SECRET_KEY: superlongsecretforsupersecureapplication32bytes
      SPRING_PROFILES_ACTIVE: dev
      CONFIRMATION_URL: http://localhost:5173/verify-email
      RESET_URL: http://localhost:5173/resetare-parola
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/DeLaSursa:/app
      - ~/.gradle:/home/gradle/.gradle
    restart: unless-stopped


  # --- Vite React Frontend ---
  frontend:
    build:
      context: ./Frontend/delasursa
    container_name: vite-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/delasursa:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend:8080

# --- Named volumes ---
volumes:
  pgdata:
  node_modules_frontend:
